#!/usr/bin/env python3
"""
pxVM Runner - Execute VM bytecode and render to PXTERM

Connects pxVM syscalls → PXTERM → GPU terminal → PNG
"""
from __future__ import annotations
import sys
from pathlib import Path
from pxvm import PxVM
from pxos_llm_terminal import run_pxterm_file


def run_vm_program(bytecode_file: str, output_png: str = None, save_pxterm: bool = True):
    """
    Run a pxVM program and render its output

    Args:
        bytecode_file: Path to .pxvm bytecode file
        output_png: Output PNG filename (default: derived from bytecode_file)
        save_pxterm: Whether to save intermediate PXTERM file
    """
    # Load bytecode
    with open(bytecode_file, 'rb') as f:
        bytecode = f.read()

    print(f"Loaded {len(bytecode)} bytes from {bytecode_file}")

    # Create and run VM
    vm = PxVM(imperfect=True)
    vm.load(bytecode)

    print("Executing pxVM...")
    vm.run()

    if vm.state.halted:
        print(f"VM halted at PC={vm.state.pc}")
    else:
        print(f"VM stopped at PC={vm.state.pc}")

    print(f"Registers: R0-R7 = {vm.state.registers}")

    # Get syscall output
    sysout = vm.get_sysout()
    print(f"Generated {len(sysout)} PXTERM instructions")

    if not sysout:
        print("Warning: VM produced no PXTERM output")
        return

    # Determine output filenames
    if output_png is None:
        base = Path(bytecode_file).stem
        output_png = f"{base}.png"

    pxterm_file = Path(bytecode_file).stem + ".pxterm"

    # Add canvas setup if not present
    has_canvas = any(line.startswith("CANVAS") for line in sysout)
    if not has_canvas:
        sysout.insert(0, "CANVAS 800 600")

    # Add DRAW command if not present
    has_draw = any(line.startswith("DRAW") for line in sysout)
    if not has_draw:
        sysout.append(f"DRAW {output_png}")

    # Save PXTERM file
    if save_pxterm:
        with open(pxterm_file, 'w') as f:
            f.write("# Generated by pxVM syscalls v0.1\n")
            for line in sysout:
                f.write(line.rstrip() + "\n")
        print(f"Saved PXTERM to {pxterm_file}")

    # Execute PXTERM
    print(f"\nRendering via PXTERM...")
    try:
        # Write temporary PXTERM file for execution
        with open(pxterm_file, 'w') as f:
            f.write("# Generated by pxVM syscalls v0.1\n")
            for line in sysout:
                f.write(line.rstrip() + "\n")

        run_pxterm_file(pxterm_file, output_png, imperfect=True)
        print(f"\n✓ VM program rendered successfully: {output_png}")

    except Exception as e:
        print(f"Error executing PXTERM: {e}")
        raise


def main():
    if len(sys.argv) < 2:
        print("Usage: python pxvm_run.py <program.pxvm> [output.png]")
        print("\nExample:")
        print("  python pxvm_run.py examples/hello.pxvm")
        print("  python pxvm_run.py examples/window.pxvm window_output.png")
        sys.exit(1)

    bytecode_file = sys.argv[1]
    output_png = sys.argv[2] if len(sys.argv) > 2 else None

    if not Path(bytecode_file).exists():
        print(f"Error: File not found: {bytecode_file}")
        sys.exit(1)

    run_vm_program(bytecode_file, output_png)


if __name__ == "__main__":
    main()
