#!/usr/bin/env python3
"""
pxvm_run_scene.py - Assemble and run a pxVM pseudo-assembly program.
"""

import subprocess
import textwrap
from pxos_assembler import PxOSAssembler
from pxvm import PxVM
from pxos_gpu_terminal import PxOSTerminalGPU, run

def run_pxvm_and_render(program_words, entry_point, pxterm_path="vm_scene.pxterm"):
    term = PxOSTerminalGPU(offscreen=False)
    vm = PxVM()
    vm.host_terminal = term
    vm.load_program(program_words, entry_point)

    def animation_frame():
        for _ in range(10): # Run 10 instructions per frame
            vm.step()

        with open(pxterm_path, "w") as f:
            f.write("# Generated by pxVM syscalls v0.1\n")
            f.write("\n".join(vm.sysout))
        term.draw_frame()
        if not vm.halted:
            term.canvas.request_draw(animation_frame)

    animation_frame()
    run()

def run_self_hosting_demo():
    """Assemble and run the self-hosting assembler demo."""
    with open("assembler.asm", "r") as f:
        assembler_asm = f.read()

    pseudo_asm = textwrap.dedent(
        """
        ; Boot
        FORK                    ; spawn assembler
        JMP MAIN_LOOP

        MAIN_LOOP:
            SYSCALL 13 ; SLEEP 100
            JMP MAIN_LOOP
        """
    )

    print("Assembling assembler...")
    assembler = PxOSAssembler()
    assembler_words, assembler_entry = assembler.assemble(assembler_asm)

    print("Assembling boot sequence...")
    program_words, entry_point = assembler.assemble(pseudo_asm)

    full_program = program_words + assembler_words

    print("Assembly successful.")

    run_pxvm_and_render(full_program, entry_point)

def main():
    print("Select a demo to run:")
    print("1. Self-hosting assembler")
    choice = input("> ")
    if choice == "1":
        run_self_hosting_demo()
    else:
        print("Invalid choice.")

if __name__ == "__main__":
    main()
