#!/usr/bin/env python3
"""
pxvm_run_scene.py - Run a pxVM bytecode file and render its output.
Usage:
  python pxvm_run_scene.py <vm_program.bin>
"""

import sys
import subprocess
from pxvm import PxVM

def run_pxvm_and_render(bytecode: bytes, pxterm_path="vm_scene.pxterm"):
    vm = PxVM(bytecode)
    vm.run()

    with open(pxterm_path, "w") as f:
        f.write("# Generated by pxVM syscalls v0.1\n")
        f.write("\n".join(vm.sysout))

    subprocess.run(
        [sys.executable, "pxos_llm_terminal.py", pxterm_path],
        check=True,
    )

def main():
    if len(sys.argv) != 2:
        print("Usage: pxvm_run_scene.py <vm_program.bin>")
        sys.exit(1)

    in_path = sys.argv[1]

    with open(in_path, "rb") as f:
        bytecode = f.read()

    run_pxvm_and_render(bytecode)

if __name__ == "__main__":
    main()
